<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Authors>Aliwwwmo</Authors>
    <Description>Auto Network Failover for Zero-Downtime</Description>
    <Copyright>Copyright © 2026 Aliwwwmo. All</Copyright>
    <ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
    <Version>1.1.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\AliSharafi.mp4" />
    <None Remove="Assets\Comp 1_1 %282%29.mp4" />
    <None Remove="Assets\Comp 1_1.mp4" />
    <None Remove="Assets\telegram-logo-png-0.png" />
    <None Remove="Assets\Untitled-1.jpg" />
    <None Remove="Assets\videoplayback %282%29.mp4" />
    <None Remove="Assets\videoplayback.mp4" />
    <None Remove="Assets\videoplayback.wmv" />
    <None Remove="Assets\videoplayback22.mp4" />
    <None Remove="Assets\videoplayback_1.gif" />
    <None Remove="Assets\Youtube_logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\telegram-logo-png-0.png" />
    <Resource Include="Assets\Untitled-1.jpg" />
    <Content Include="Assets\AliSharafi.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\Comp 1_1 (2).mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Comp 1_1.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\favicon.ico" />
    <Resource Include="Assets\videoplayback (2).mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <EmbeddedResource Include="Assets\videoplayback22.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Resource Include="Assets\videoplayback.mp4" />
    <Resource Include="Assets\videoplayback.wmv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\videoplayback_1.gif" />
    <Resource Include="Assets\Youtube_logo.png" />
  </ItemGroup>

</Project>
